# Generated by Django 4.2.3 on 2023-07-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coengage', '0003_customuser_is_verified_customuser_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='otp_attempts_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='otp_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
