# Generated by Django 4.2.3 on 2023-07-30 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coengage', '0004_customuser_otp_attempts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.URLField(default='https://coengage-bucket.s3.us-west-1.amazonaws.com/default_profile_picture.png'),
        ),
    ]
