# Generated by Django 4.2.3 on 2023-09-17 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coengage', '0008_rename_vote_postvote_comment_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.URLField(default='https://hackersclub-production-user-content-us-west-1.s3.us-west-1.amazonaws.com/default_profile_picture.png'),
        ),
    ]
