# Generated by Django 4.2.3 on 2023-09-18 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coengage', '0009_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
