# Generated by Django 4.2.3 on 2023-10-16 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coengage', '0010_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
